### ISSUE TITLE
StaticInjectorError(AppModule)[AutosizeDirective -> WindowRef]

### ISSUE THREAD

**Issue by Rominet13** [chrum/ngx-autosize#76] opened 2021-06-17 13:15 UTC
Hi
I get this error when using autosize 1.8.4 with CdkDrag (@angular/cdk": "^8.2.3")
(it happens when dropping a textarea with autosize)

  ERROR NullInjectorError: StaticInjectorError(AppModule)[AutosizeDirective -> WindowRef]: 
    StaticInjectorError(Platform: core)[AutosizeDirective -> WindowRef]: 
      NullInjectorError: No provider for WindowRef!
      at NullInjector.get (core.js:855)
      at resolveToken (core.js:17514)
      at tryResolveToken (core.js:17440)
      at StaticInjector.get (core.js:17266)
      at resolveToken (core.js:17514)
      at tryResolveToken (core.js:17440)
      at StaticInjector.get (core.js:17266)
      at resolveNgModuleDep (core.js:30393)
      at NgModuleRef_.get (core.js:31578)
      at resolveDep (core.js:32143)

Maybe this link can help:
https://brianflove.com/2018-01-11/angular-window-provider/
(i 'm going to try this link when i got a bit of time, to see if it removes this errors)

Thanks for the lib.

**Comment by chrum** [comment] 2021-12-20 15:17
Hey, i couldnt reproduce it i am afraid but i added a demo https://chrum.it/pages/ngx-autosize/ (last example) 

please let me know if you still have this issue

**Comment by Rominet13** [comment] 2021-12-20 15:34
Hey
The error happens at the drop, not during the drag. A simple example would be a drag and drop between two list. I think it is when creating the same text area as a consequence of the drop. I can't have access to my projects for 2 weeks (vacation you know...), I can't remember what workaround I have used (I will try to check it as soon as I can)
Thanks for the demo by the way 😅.

**Comment by chrum** [comment] 2021-12-20 15:40
ahhh right, dropping (you mentioned that in your original comment, sorry)
will try checking it

**Comment by chrum** [comment] 2021-12-20 16:09
hey,
I changed my example to do actual drag&drop https://github.com/chrum/ngx-autosize/commit/a0520d4ffc4c13cf467d42aaaada66aa60a26330

its basically copy&paste from here https://v7.material.angular.io/cdk/drag-drop/overview#transferring-items-between-lists

and i still cant reproduce the issue, let me know if you did it differently

PS. in my demo text changes in text areas are not preserved

**Comment by Rominet13** [comment] 2021-12-20 16:41
Ok. Thanks.
I will check it the 3 of January when I m back.
You can close it.

**Closed as completed** 2021-12-20 17:10 UTC
Labels: bug
