### ISSUE TITLE
Line height / row size logic is not perfect

### ISSUE THREAD

**Issue by chrum** [chrum/ngx-autosize#43] opened 2020-02-29 07:59 UTC
From @mrkorsar:

>  there are different height in different browsers. In Chrome textarea has 38px of height for 1 row and in FireFox this value is 55px. It looks like a bug

**Comment by fmuscolino** [comment] 2020-05-12 10:55
Hi! Any update on this? In our app we have lot of textareas with 1 row and the layout looks very weird.
Thanks!

**Comment by chrum** [comment] 2020-05-12 10:57
@fmuscolino hey
did you try setting native textarea prop 'rows' to 1 ?

**Comment by fmuscolino** [comment] 2020-05-12 11:08
Thanks for your fast reply! 
Yes I already tried, but nope. For instance, with 0.8rem font-size and 1rem line-height, in chrome height is 33px, in firefox is 39px.

![textarea_chrome](https://user-images.githubusercontent.com/59616947/81677802-8736d180-9451-11ea-9557-3829578b6039.png)
![textarea_firefox](https://user-images.githubusercontent.com/59616947/81677147-f6f88c80-9450-11ea-841f-49687f50b89b.png)

I know is a small difference, but we have some forms where fields on same row, in Firefox, are not aligned because of this

**Comment by fmuscolino** [comment] 2020-05-19 15:36
Ok I got it

The problem is that in FF if a textarea has only one row, then setting overflow:'auto' or overflow:'hidden' will result in two different heights (this doesn't happen in Chrome)

In the code there's a point (line 168) where you set the overflow of the textarea to 'hidden', but you already calculated the height using the clone that had overflow: 'auto'.
So, a simple fix is to set also overflow of clone to 'hidden' and then recalculate computed height of clone.

If it's something that you can do (it's only few lines), or I can open a PR, as you prefer!
Thanks

**Comment by chrum** [comment] 2020-05-19 16:47
hey @fmuscolino 
awesome, i will check your finding shortly :)

**Comment by chrum** [comment] 2020-05-19 17:11
shiiiiit :D its dead obvious that clone should have overflow: hidden

**Comment by chrum** [comment] 2020-05-19 17:13
I just noticed that 'useImportant' is broken... are you in a super hurry? I will deal with that one too and then make a build... what do you say?

**Comment by chrum** [comment] 2020-05-19 18:59
ok check 'next' channel
`npm install ngx-autosize@next`

**Comment by fmuscolino** [comment] 2020-05-20 08:17
Just tried, works like a charm! Perfect!

We'll use the 'next' until the 1.8.0 will be released, thanks for your fast help!

**Closed as completed** 2020-05-24 18:30 UTC
Labels: bug
